# example compose file for dcsh

version: '3.4'

x-dcsh:
  sudo: true

  # jobs are specifically for running services once with 'dc run --rm'
  jobs:
    test:
      - serivce: myapp
      - args: [hello, dcsh, world]
    python:
      - service: python
      - interactive: true

  # scripts are turned into BASH functions
  scripts:
    do-foo: |
      # Runs a foo command
      # All arguments are displayed through "echo" as passed
      echo "running foo"
      echo "$@"
      echo "done with foo"

  # environment vars added to the subshell on launch
  environment:
    foo: bar


services:
  myapp:
    build: .
    volumes:
      - .:/workspace
  python:
    image: python:latest
    volumes:
      - .:/workspace
    entrypoint: /workspace
