# example compose file for dcsh

version: '3.4'

# Environment settings for use behind a corporate proxy and/or using mirror
# services like Nexus or self-hosted Pypi.
x-walled-garden-args: &walled-garden-args
  http_proxy:
  https_proxy:
  no_proxy:
  PIP_INDEX_URL:
  PIP_TRUSTED_HOST:
 
# DCSH configuration.
x-dcsh:
  tasks:
    sh:
      help: 'runs shell on python-dev service'
      service: python-dev
      args: sh
    python:
      help: 'runs python interpreter'
      service: python-dev
      args: python 
    pydoc:
      help: 'help for python'
      service: python-dev
      args: python -m pydoc
    test:
      help: 'runs unit tests through coverage'
      service: python-dev
      args: coverage run setup.py test 
    coverage:
      help: 'displays coverage report'
      service: python-dev
      args: coverage report -m
    lint:
      help: 'lints the project'
      service: python-dev
      args: flake8 dcsh/*.py tests/*.py

services:
  python-dev:
    build:
      context: .
      args:
        <<: *walled-garden-args
    volumes:
      - .:/workspace
    working_dir: /workspace
