# example compose file for dcsh

version: '3.4'

x-dcsh:
  sudo: true

  # scripts are turned into BASH functions
  scripts:
    do-foo: |
      # Runs a foo command
      # All arguments are displayed through "echo" as passed
      echo "running foo"
      echo "$@"
      echo "done with foo"
    test: 'dc run --rm myapp' 

  # environment vars added to the subshell on launch
  environment:
    foo: bar


services:
  myapp:
    build: .
    volumes:
      - .:/workspace
