# example compose file for dcsh

version: '3.4'

x-dcsh:
  sudo: true

  # functions are turned into BASH functions
  functions:
    do-foo: |
      # runs a foo command
      # all arguments are displayed through "echo" as passed
      echo "running foo"
      echo "$@"
      echo "done with foo"

  # scripts are automatically prefixed with the `dc` command alias
  scripts:
    test: 'run --rm myapp' 

  # environment vars added to the subshell on launch
  environment:
    foo: bar


services:
  myapp:
    build: .
    volumes:
      - .:/workspace
